services:
  frontend:
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NODE_ENV: ${NODE_ENV}
    container_name: werkzeugkiste-frontend
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOSTNAME=${HOSTNAME}
      - PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:3000"
    restart: unless-stopped

  backend:
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
        NODE_ENV: ${NODE_ENV}
    container_name: werkzeugkiste-backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOSTNAME=${HOSTNAME}
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:4000"
    restart: unless-stopped

networks:
  default:
    driver: bridge
