services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: werkzeugkiste-frontend
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOSTNAME=${HOSTNAME}
      - PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: werkzeugkiste-backend
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOSTNAME=${HOSTNAME}
      - PORT=${BACKEND_PORT}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
    ports:
      - "${BACKEND_PORT}:4000"
    restart: unless-stopped

networks:
  default:
    driver: bridge
