services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: werkzeugkiste
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped