name: Build, Push and Deploy

on:
  pull_request:
    types: [closed]
    branches: [ main ]

  workflow_dispatch:
    inputs:
      question:
        description: 'NextJS on top?'
        required: false
        default: 'FR'
        type: choice
        options:
          - 'FR'
          - 'FR FR'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/werkzeugkiste-frontend:latest

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/werkzeugkiste-backend:latest